(function(root,factory){var cases=factory();if(typeof module!=="undefined"&&module.exports)module.exports=cases;else (root.TZO_CASE_PARTS=root.TZO_CASE_PARTS||[]).push(cases);})(globalThis,function(){
"use strict"; var MINUTE=60000; var cases=[]; function add(id,name,run){cases.push({id:id,name:name,run:run});} function eq(a,b,msg){if(JSON.stringify(a)!==JSON.stringify(b))throw new Error(msg+"\nexpected="+JSON.stringify(b)+"\nactual="+JSON.stringify(a));} function ok(x,msg){if(!x)throw new Error(msg);}
var NOW=Date.UTC(2026,9,6,12); function st(c,s,e,l){return {cities:c,schedules:s.map(function(x){return {start:x[0],end:x[1],lunch:x[2]||0};}),date:undefined,hourFormat:24,meetingLength:60};} function cities(ids,C){return ids.map(function(id){for(var i=0;i<C.length;i++)if(C[i].id===id)return C[i];throw new Error("missing city "+id);});}
add("C01","Grid lengths",function(ctx){var C=ctx.cities,E=ctx.engine; [["new-york","2026-03-08",92],["new-york","2026-11-01",100],["london","2026-03-29",92],["london","2026-10-25",100],["seoul","2026-10-06",96]].forEach(function(x){var cs=cities([x[0]],C),s={cities:cs.concat(cities([x[0]==="seoul"?"london":"seoul"],C)[0]),schedules:[{start:540,end:1080,lunch:0},{start:540,end:1080,lunch:0}],date:x[1],hourFormat:24,meetingLength:60};ok(E.computeOverlap(s,{nowMs:NOW}).baseSlotCount===x[2],x[0]+" grid");});});
add("C02","New York + London DST",function(ctx){var E=ctx.engine,C=ctx.cities; [["2026-03-10",5],["2026-10-27",5],["2026-11-10",4]].forEach(function(x){var s={cities:cities(["new-york","london"],C),schedules:[{start:540,end:1080,lunch:0},{start:540,end:1080,lunch:0}],date:x[0],hourFormat:24,meetingLength:60},r=E.computeOverlap(s,{nowMs:NOW});ok(r.overlapRanges.reduce(function(n,z){return n+z.lengthMin;},0)===x[1]*60,x[0]+" duration");});});
add("C03","Seoul + London",function(ctx){var E=ctx.engine,C=ctx.cities,s={cities:cities(["seoul","london"],C),schedules:[{start:540,end:1080,lunch:0},{start:540,end:1080,lunch:0}],date:"2026-07-15",hourFormat:24,meetingLength:60},r=E.computeOverlap(s,{nowMs:NOW});eq([r.overlapRanges[0].startUtc,r.overlapRanges[0].endUtc],[Date.UTC(2026,6,15,8),Date.UTC(2026,6,15,9)],"Seoul London");});
add("C04","Seoul + New York fallback",function(ctx){var E=ctx.engine,C=ctx.cities,s={cities:cities(["seoul","new-york"],C),schedules:[{start:540,end:1080,lunch:0},{start:540,end:1080,lunch:0}],date:"2026-01-15",hourFormat:24,meetingLength:60},r=E.computeOverlap(s,{nowMs:NOW});eq(r.overlapRanges,[],"no overlap");ok(r.recommendation.kind==="fallback","fallback");eq([r.recommendation.startUtc,r.recommendation.endUtc],[Date.UTC(2026,0,14,22),Date.UTC(2026,0,14,23)],"fallback instant");});
add("C05","Kolkata + Kathmandu",function(ctx){var E=ctx.engine,C=ctx.cities,s={cities:cities(["kolkata","kathmandu"],C),schedules:[{start:540,end:1080,lunch:0},{start:540,end:1080,lunch:0}],date:"2026-10-06",hourFormat:24,meetingLength:60},r=E.computeOverlap(s,{nowMs:NOW});eq([r.overlapRanges[0].startUtc,r.overlapRanges[0].endUtc],[Date.UTC(2026,9,6,3,30),Date.UTC(2026,9,6,12,15)],"15-minute zone");});
add("C06","Overnight lunch has no effect",function(ctx){var E=ctx.engine,C=ctx.cities;function run(l){return E.computeOverlap({cities:cities(["seoul","london"],C),schedules:[{start:1320,end:360,lunch:l},{start:1320,end:360,lunch:l}],date:"2026-10-06",hourFormat:24,meetingLength:60},{nowMs:NOW}).overlapRanges.map(function(x){return [x.startUtc,x.endUtc];});}eq(run(0),run(1),"lunch has no effect");});add("C07","Date line offsets",function(ctx){var E=ctx.engine,C=ctx.cities,s={cities:cities(["honolulu","kiritimati"],C),schedules:[{start:540,end:1080,lunch:0},{start:540,end:1080,lunch:0}],date:"2026-10-06",hourFormat:24,meetingLength:60},r=E.computeOverlap(s,{nowMs:NOW});eq([r.overlapRanges[0].startUtc,r.overlapRanges[0].endUtc],[Date.UTC(2026,9,6,19),Date.UTC(2026,9,7,4)],"date line");ok(r.overlapRanges[0].perCity[1].dayOffset===1,"+1 day");});
add("C08","Five cities and duplicates rejected upstream",function(ctx){var E=ctx.engine,C=ctx.cities,s={cities:cities(["seoul","tokyo","london","new-york","sydney"],C),schedules:[{start:540,end:1080,lunch:0},{start:540,end:1080,lunch:0},{start:540,end:1080,lunch:0},{start:540,end:1080,lunch:0},{start:540,end:1080,lunch:0}],date:"2026-10-06",hourFormat:24,meetingLength:60};ok(E.computeOverlap(s,{nowMs:NOW}).slots.length>0,"five cities");});
add("C09","Overnight base and full grid",function(ctx){var E=ctx.engine,C=ctx.cities; ["2026-03-08","2026-11-01","2026-10-06"].forEach(function(d){var s={cities:cities(["new-york","london"],C),schedules:[{start:1320,end:360,lunch:0},{start:540,end:1080,lunch:0}],date:d,hourFormat:24,meetingLength:60},r=E.computeOverlap(s,{nowMs:NOW});ok(r.gridSlotCount>r.baseSlotCount,"overnight grid");});});
add("C10","Session mask",function(ctx){var E=ctx.engine,C=ctx.cities,s={cities:cities(["seoul","london"],C),schedules:[{start:1320,end:360,lunch:0},{start:1320,end:360,lunch:0}],date:"2026-10-06",hourFormat:24,meetingLength:60},r=E.computeOverlap(s,{nowMs:NOW});for(var i=0;i<24;i++)ok(!r.slots[i].inSession,"early tail excluded");});
add("C11","End time 0000",function(ctx){var E=ctx.engine,C=ctx.cities,s={cities:cities(["seoul","london"],C),schedules:[{start:840,end:0,lunch:0},{start:540,end:1080,lunch:0}],date:"2026-10-06",hourFormat:24,meetingLength:60},r=E.computeOverlap(s,{nowMs:NOW});ok(r.gridSlotCount===r.baseSlotCount,"empty overnight tail");});
add("C12","Shorter overlap uses fallback",function(ctx){var E=ctx.engine,C=ctx.cities,s={cities:cities(["seoul","london"],C),schedules:[{start:540,end:1080,lunch:0},{start:540,end:585,lunch:0}],date:"2026-07-15",hourFormat:24,meetingLength:60},r=E.computeOverlap(s,{nowMs:NOW});ok(!r.meetingFits&&r.recommendation.kind==="fallback","short overlap fallback");eq([r.overlapRanges[0].startUtc,r.overlapRanges[0].endUtc],[Date.UTC(2026,6,15,8),Date.UTC(2026,6,15,8,45)],"short overlap");});
add("C13","Night minutes only when outside",function(ctx){var E=ctx.engine,C=ctx.cities,s={cities:cities(["seoul","london"],C),schedules:[{start:1320,end:360,lunch:0},{start:540,end:1080,lunch:0}],date:"2026-10-06",hourFormat:24,meetingLength:60},r=E.computeOverlap(s,{nowMs:NOW});ok(r.recommendation!==null,"recommendation");});
add("C14","Midnight end label",function(ctx){var E=ctx.engine,C=ctx.cities,s={cities:cities(["seoul","tokyo"],C),schedules:[{start:1080,end:0,lunch:0},{start:1080,end:0,lunch:0}],date:"2026-10-06",hourFormat:24,meetingLength:60},r=E.computeOverlap(s,{nowMs:NOW});ok(r.overlapRanges.length>0,"midnight range");var p=r.overlapRanges[0].perCity[0];ok(p.end.hh===0&&p.endDateDiffers===true,"midnight end differs");});
add("C15","ICS determinism",function(ctx){var E=ctx.engine,a={nowMs:NOW,uid:"abc@example",startUtc:NOW,endUtc:NOW+3600000,title:"Test, 서울",description:"A;B\\C\nD"};eq(E.buildIcs(a),E.buildIcs(a),"ICS deterministic");});
add("C16","Runtime tz guard",function(ctx){["America/New_York","Europe/London","Asia/Seoul","Asia/Kolkata","Asia/Kathmandu","Pacific/Auckland","Pacific/Kiritimati","Australia/Sydney"].forEach(function(t){ok(ctx.engine.resolveTimeZone(t)===t,"timezone "+t);});});
add("C17","Repeated-hour overnight tail",function(ctx){var E=ctx.engine,C=ctx.cities,s={cities:cities(["new-york","london"],C),schedules:[{start:1320,end:90,lunch:0},{start:1320,end:90,lunch:0}],date:"2026-10-31",hourFormat:24,meetingLength:60},r=E.computeOverlap(s,{nowMs:NOW});eq(r.baseSlotCount,96,"base");eq(r.gridSlotCount,106,"full grid");eq(r.tailEndUtc,Date.UTC(2026,10,1,6,30),"tail");});
add("C18","Southern hemisphere grids",function(ctx){var E=ctx.engine,C=ctx.cities; [["sydney","2026-10-04",92],["sydney","2026-04-05",100],["auckland","2026-09-27",92],["auckland","2026-04-05",100]].forEach(function(x){var s={cities:cities([x[0],"seoul"],C),schedules:[{start:540,end:1080,lunch:0},{start:540,end:1080,lunch:0}],date:x[1],hourFormat:24,meetingLength:60};eq(E.computeOverlap(s,{nowMs:NOW}).baseSlotCount,x[2],x[0]+" grid");});});
add("C19","Equal start end URL repair",function(ctx){var E=ctx.engine,C=ctx.cities,s=E.parseUrlState("?c=seoul,london&s=0900,1000&e=1800,1000&l=0,0&d=2026-10-06&f=24&m=60",{cities:C,detectedTz:"Asia/Seoul",nowMs:NOW});eq(s.schedules,[{start:540,end:1080,lunch:0},{start:540,end:1080,lunch:0}],"repair");E.computeOverlap(s,{nowMs:NOW});var bad=false;try{E.computeOverlap({cities:s.cities,schedules:[{start:540,end:540,lunch:0},{start:540,end:1080,lunch:0}],date:s.date,hourFormat:24,meetingLength:60},{nowMs:NOW});}catch(e){bad=true;}ok(bad,"direct equal schedule throws");});
add("C20","Midnight-gap zones",function(ctx){var R=ctx.reference;["America/Santiago","America/Havana","Africa/Cairo","Asia/Beirut"].forEach(function(tz){var candidates={},prev=null;for(var day=0;day<=366;day++){var t=Date.UTC(2026,0,1,12)+day*86400000,p=R.localParts(t,tz),off=Date.UTC(p.y,p.m-1,p.d,p.hh,p.mm,p.ss)-Math.floor(t/1000)*1000;if(prev!==null&&off!==prev)candidates[day]=1;prev=off;}var found=false;Object.keys(candidates).forEach(function(k){var base=Date.UTC(2026,0,1)+Number(k)*86400000;for(var delta=-2;delta<=2;delta++){var dms=base+delta*86400000,pd=new Date(dms),y=pd.getUTCFullYear(),m=pd.getUTCMonth()+1,d=pd.getUTCDate(),date=y+"-"+String(m).padStart(2,"0")+"-"+String(d).padStart(2,"0"),seen=false;for(var t=dms-36*3600000;t<=dms+36*3600000;t+=60000){var q=R.localParts(t,tz);if(q.y===y&&q.m===m&&q.d===d&&q.hh===0){seen=true;break;}}if(!seen){found=true;var b=ctx.engine.localMidnightUtc(tz,y,m,d),p0=ctx.engine.localParts(b,tz),p1=ctx.engine.localParts(b-60000,tz);ok(p0.y===y&&p0.m===m&&p0.d===d,"gap date "+date);ok(!(p1.y===y&&p1.m===m&&p1.d===d),"previous minute "+date);}}});if(!found)throw new Error("no midnight-gap date discovered for "+tz);});});add("C21","summaryText formats",function(ctx){var E=ctx.engine,C=ctx.cities,s={cities:cities(["seoul","london"],C),schedules:[{start:540,end:1080,lunch:0},{start:540,end:1080,lunch:0}],date:"2026-07-15",hourFormat:24,meetingLength:60},r=E.computeOverlap(s,{nowMs:NOW});var a=E.summaryText(r,{locale:"en-US",hourFormat:24}),b=E.summaryText(r,{locale:"en-US",hourFormat:12});ok(a.indexOf("17:00")>=0&&a.indexOf("09:00")>=0,"24h summary");ok(b.indexOf("5:00 PM")>=0&&b.indexOf("9:00 AM")>=0,"12h summary");ok(a.indexOf("\u202f")<0&&a.indexOf("\u00a0")<0&&a.indexOf("24:00")<0,"summary whitespace");eq(a,E.summaryText(r,{locale:"en-US",hourFormat:24}),"summary deterministic");});
add("C22","same timezone pairs",function(ctx){var E=ctx.engine,C=ctx.cities,s={cities:cities(["new-york","toronto"],C),schedules:[{start:540,end:1080,lunch:0},{start:540,end:1080,lunch:0}],date:"2026-10-06",hourFormat:24,meetingLength:60},r=E.computeOverlap(s,{nowMs:NOW});eq(r.sameTimezonePairs,[{a:0,b:1,reason:"same-offset"}],"NY Toronto");var s2={cities:cities(["seoul","london"],C),schedules:s.schedules,date:s.date,hourFormat:24,meetingLength:60};eq(E.computeOverlap(s2,{nowMs:NOW}).sameTimezonePairs,[],"Seoul London");});
add("C23","24-hour date line pair",function(ctx){var E=ctx.engine,C=ctx.cities,s={cities:cities(["honolulu","kiritimati"],C),schedules:[{start:540,end:1080,lunch:0},{start:540,end:1080,lunch:0}],date:"2026-10-06",hourFormat:24,meetingLength:60},r=E.computeOverlap(s,{nowMs:NOW});eq([r.overlapRanges[0].startUtc,r.overlapRanges[0].endUtc],[Date.UTC(2026,9,6,19),Date.UTC(2026,9,7,4)],"date line");});
add("C24","Performance sanity",function(ctx){var E=ctx.engine,C=ctx.cities,s={cities:cities(["new-york","london","seoul","sydney","tokyo"],C),schedules:[{start:1320,end:360,lunch:0},{start:540,end:1080,lunch:1},{start:540,end:1080,lunch:1},{start:540,end:1080,lunch:0},{start:540,end:1080,lunch:0}],date:"2026-11-01",hourFormat:24,meetingLength:90};var t=Date.now();for(var i=0;i<20;i++)E.computeOverlap(s,{nowMs:NOW});ok(Date.now()-t<2000,"performance");});
return cases;});
